name: SQL Server Deployment

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SQL Server tools
        run: |
          sudo apt-get update
          sudo apt-get install -y mssql-tools unixodbc-dev

      - name: Build SQL Server project
        run: msbuild ./GA-SQLServer2022-SDK-DBProject.sqlproj /t:Build /p:Configuration=Release

      - name: Publish SQL Server project
        run: msbuild GA-SQLServer2022-SDK-DBProject.sqlproj /t:Publish /p:Configuration=Release /p:SqlPublishProfilePath=PublishProfile.publish.xml

      - name: Deploy SQL Server project
        run: sqlcmd -S tcp:15.188.231.120,1433 -d testgit -U NCPAdmin -P fgDS67:54 -i GA-SQLServer2022-SDK-DBProject.sql

