on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SQL Server Data Tools (SSDT)
        run: |
          sudo apt-get update
          sudo apt-get install -y mssql-tools
          sudo apt-get install -y msbuild
          sudo apt-get install -y sqlpackage

      - name: Build and Deploy SQL Server project
        run: |
          msbuild /t:Build /p:Configuration=Release GitHub-SQLServer2022-SDK-DBProject.sqlproj
          sqlpackage /Action:Publish /SourceFile:./GitHub-SQLServer2022-SDK-DBProject/bin/Release/GitHub-SQLServer2022-SDK-DBProject.dacpac /TargetConnectionString:"Server=tcp:15.188.231.120,1433;Initial Catalog=testgit;Persist Security Info=False;User ID=NCPAdmin;Password=fgDS67:54;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=True;Connection Timeout=120;" /p:BlockOnPossibleDataLoss=False



